# Site settings
title: 2-bit Baugh-Wooley Multiplier
email: akhilreddygujju@example.com # Replace with your actual email
description: "VLSI design and simulation of a 2-bit Baugh-Wooley signed multiplier using MAGIC and NGspice."
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://akhilreddygujju.github.io/baughwooley" # Replace with your GitHub Pages URL
github_username: akhilreddygujju # Replace with your GitHub username

# Build settings
markdown: kramdown
theme: minima # Or your chosen theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Theme settings (for a hypothetical "silicon-blue" theme - customize as needed)
theme_color: "#2962FF" # Deep blue
background_color: "#EEEEEE" # Light gray
text_color: "#424242" # Dark gray
accent_color: "#90CAF9" # Light blue
highlight_color: "#E1F5FE" # Very light blue for code highlights

# Navigation (if using a custom theme)
nav:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/README.md # Adjust path if needed
  - title: GitHub
    url: "https://github.com/akhilreddygujju/baughwooley"

# Footer settings (if using a custom theme)
footer:
  copyright: "&copy; Akhil Reddy Gujju 2024"
  social:
    github: "https://github.com/akhilreddygujju"

# Custom CSS (if needed)
sass:
  style: compressed

# Plugins (if needed)
plugins:
  - jekyll-seo-tag
