title: 2-bit Baugh-Wooley Signed Multiplier
description: "VLSI design and simulation of a 2-bit Baugh-Wooley signed multiplier using MAGIC and NGspice."
theme: jekyll-theme-documentation # or your preferred theme
# logo: /path/to/your/logo.png # Uncomment and set path if you have a logo
# show_downloads: true # Uncomment if you want to show download links
